---

- name: amp-proxy group
  ansible.builtin.group:
    name: amp-proxy
    state: present
    system: true

- name: amp-proxy user
  ansible.builtin.user:
    name: amp-proxy
    group: amp-proxy
    system: true
    create_home: false

- name: create amp-proxy directories
  file:
    owner: amp-proxy
    group: amp-proxy
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "/opt/amp-proxy"
    - "/opt/amp-proxy/config"
