---

- name: aps-proxy group
  ansible.builtin.group:
    name: aps-proxy
    state: present
    system: true

- name: aps-proxy user
  ansible.builtin.user:
    name: aps-proxy
    group: aps-proxy
    system: true
    create_home: false

- name: create aps-proxy directories
  file:
    owner: aps-proxy
    group: aps-proxy
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "/opt/aps-proxy"
    - "/opt/aps-proxy/config"
