---
# tasks file for escapace.observability

- ansible.builtin.include_tasks: observability.yml
  when: ansible_os_family == "RedHat"
  tags:
    - run-observability

- ansible.builtin.include_tasks: node-exporter.yml
  when: ansible_os_family == "RedHat"
  tags:
    - node-exporter
