---
# tasks file for escapace.observability

- ansible.builtin.include_tasks: observability.yml
  when: ansible_os_family == "RedHat"
  tags:
    - run-observability

- ansible.builtin.include_tasks: node-exporter.yml
  when: ansible_os_family == "RedHat"
  tags:
    - node-exporter

- name: import escapace.newrelic
  ansible.builtin.import_role:
    name: escapace.newrelic
  when: ansible_os_family == "RedHat" and observability_newrelic|bool
