---
- name: set kernel.perf_event_paranoid
  ansible.posix.sysctl:
    name: kernel.perf_event_paranoid
    value: "2"
    state: present
  when: not observability_role_debug|bool
  tags:
    - node-exporter

- name: node-exporter group
  ansible.builtin.group:
    name: node-exporter
    state: present
    system: true
  tags:
    - node-exporter

- name: node-exporter user
  ansible.builtin.user:
    name: node-exporter
    group: node-exporter
    system: true
    create_home: false
  tags:
    - node-exporter

- name: create node-exporter directories
  ansible.builtin.file:
    owner: node-exporter
    group: node-exporter
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - /opt/node-exporter
    - /opt/node-exporter/bin
  tags:
    - node-exporter

- name: create node-exporter directories
  ansible.builtin.file:
    owner: node-exporter
    group: node-exporter
    path: "{{ item }}"
    state: directory
    mode: "0750"
  with_items:
    - /opt/node-exporter/config
  tags:
    - node-exporter

- name: check node-exporter version
  ansible.builtin.slurp:
    src: /opt/node-exporter/version
  register: observability_current_node_exporter_version
  changed_when: false
  ignore_errors: true
  tags:
    - node-exporter

- name: install node-exporter
  when: observability_current_node_exporter_version.failed or observability_current_node_exporter_version['content'] | b64decode != observability_node_exporter_archive
  tags:
    - node-exporter
  block:
    - name: download node-exporter
      ansible.builtin.get_url:
        url: "{{ observability_node_exporter_archive_url }}"
        dest: /tmp/{{ observability_node_exporter_archive }}
        checksum: sha256:{{ observability_node_exporter_archive_checksum_url }}
        mode: "0660"
      changed_when: false

    - name: extract node-exporter
      ansible.builtin.unarchive:
        src: /tmp/{{ observability_node_exporter_archive }}
        dest: /opt/node-exporter/bin
        remote_src: true
        extra_opts: [--strip-components=1]
      changed_when: false

    - name: move node-exporter
      ansible.builtin.copy:
        src: /opt/node-exporter/bin/node_exporter
        dest: /opt/node-exporter/bin/node-exporter
        remote_src: true
        owner: node-exporter
        group: node-exporter
        mode: "0755"

    - name: remove node_exporter
      ansible.builtin.file:
        path: /opt/node-exporter/bin/node_exporter
        state: absent

    - name: remove archive
      ansible.builtin.file:
        path: /tmp/{{ observability_node_exporter_archive }}
        state: absent

    - name: chcon node-exporter binary
      ansible.builtin.file:
        path: /opt/node-exporter/bin/node-exporter
        owner: node-exporter
        group: node-exporter
        mode: "0755"
        setype: bin_t
        seuser: system_u

    - name: write version
      ansible.builtin.copy:
        content: "{{ observability_node_exporter_archive }}"
        dest: /opt/node-exporter/version
        owner: root
        group: root
        mode: "0644"

- name: create a node-exporter symbolic link
  ansible.builtin.file:
    src: /opt/node-exporter/bin/node-exporter
    dest: /usr/bin/node-exporter
    owner: node-exporter
    group: node-exporter
    mode: "0755"
    state: link
  tags:
    - node-exporter

- name: create node-exporter service
  ansible.builtin.template:
    src: templates/node-exporter.service.j2
    dest: /usr/lib/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - observability daemon-reload
  tags:
    - node-exporter
